var navi_cate_00000000_code = new Array ("sub1_1_1","7d3616f4","sub3_1","sub00_00","sub2_1","sub1_3_1","sub1_2_1","sub4_1")
var navi_cate_00000000_menu_subject = new Array ("회사소개","평창카운티<span>노인복지주택</span>","위례 빌리지<span>요양시설</span>","서초 빌리지<span>요양시설</span>","케어센터<span>주.야간보호센터</span>","인재채용","게시판","노인장기요양보험제도")
var navi_cate_00000000_link_url = new Array ("/page/sub1_1_1","http://pyeongchang-county.com/","/page/sub02_1","/page/Seocho_Dis","/page/sub03_1","/page/sub1_3_1","/bbs/sub05_1","/page/sub4_1")
var navi_cate_00000000_link_target = new Array ("","_blank","","","","","","")
var navi_cate_00000000_bt1 = new Array ("","","","","","","","")
var navi_cate_00000000_bt2 = new Array ("","","","","","","","")

var navi_cate_sub00_00_code = new Array ("Seocho_D","Seocho_s","Seocho_R")
var navi_cate_sub00_00_menu_subject = new Array ("서초 빌리지 소개","서초서비스·시설 안내","서초입소안내ㆍ접수")
var navi_cate_sub00_00_link_url = new Array ("/page/Seocho_Dis","/page/Seocho_sv","/page/Seocho_Rg")
var navi_cate_sub00_00_link_target = new Array ("","","")
var navi_cate_sub00_00_bt1 = new Array ("","","")
var navi_cate_sub00_00_bt2 = new Array ("","","")

var navi_cate_sub1_1_1_code = new Array ("sub1_1_2","c10f4fd5","sub1_4","sub1_1_3")
var navi_cate_sub1_1_1_menu_subject = new Array ("CEO 인사말","비전체계","공지/공시","오시는 길")
var navi_cate_sub1_1_1_link_url = new Array ("/page/sub1_1_2","/page/sub1_1_1","/bbs/sub1_4","/page/sub1_1_3")
var navi_cate_sub1_1_1_link_target = new Array ("","","","")
var navi_cate_sub1_1_1_bt1 = new Array ("","","","")
var navi_cate_sub1_1_1_bt2 = new Array ("","","","")

var navi_cate_sub1_2_1_code = new Array ("sub05_6","sub05_1","ff741636","sub05_3","sub2_3_1","dec9c651")
var navi_cate_sub1_2_1_menu_subject = new Array ("개소 예정 사업장 안내","프로그램/식단표","자원봉사안내","견학안내","상담신청","고객의 소리")
var navi_cate_sub1_2_1_link_url = new Array ("/myreg/sub05_6","/bbs/sub05_1","/page/sub1_2_1","/page/sub05_3","/bbs/sub2_3_1","/page/bl_go")
var navi_cate_sub1_2_1_link_target = new Array ("","","","","","")
var navi_cate_sub1_2_1_bt1 = new Array ("","","","","","")
var navi_cate_sub1_2_1_bt2 = new Array ("","","","","","")

var navi_cate_sub1_3_1_code = new Array ("6b068649","sub1_3_2","sub1_3_3")
var navi_cate_sub1_3_1_menu_subject = new Array ("인재상","직무소개","채용공고")
var navi_cate_sub1_3_1_link_url = new Array ("/page/sub1_3_1","/page/sub1_3_2","https://admin.kbgoldenlifecare.co.kr/recruit/main")
var navi_cate_sub1_3_1_link_target = new Array ("","","")
var navi_cate_sub1_3_1_bt1 = new Array ("","","")
var navi_cate_sub1_3_1_bt2 = new Array ("","","")

var navi_cate_sub2_1_code = new Array ("7e9b13c6","sub03_2","sub03_3")
var navi_cate_sub2_1_menu_subject = new Array ("서비스 소개","강동케어센터 소개","위례케어센터 소개")
var navi_cate_sub2_1_link_url = new Array ("/page/sub03_1","/page/sub03_2","/page/sub03_3")
var navi_cate_sub2_1_link_target = new Array ("","","")
var navi_cate_sub2_1_bt1 = new Array ("","","")
var navi_cate_sub2_1_bt2 = new Array ("","","")

var navi_cate_sub3_1_code = new Array ("54f5e29b","sub3_2_1","sub3_3")
var navi_cate_sub3_1_menu_subject = new Array ("위례빌리지 소개","서비스·시설 안내","입소안내ㆍ접수")
var navi_cate_sub3_1_link_url = new Array ("/page/sub02_1","/page/sub02_3","/page/sub02_4")
var navi_cate_sub3_1_link_target = new Array ("","","")
var navi_cate_sub3_1_bt1 = new Array ("","","")
var navi_cate_sub3_1_bt2 = new Array ("","","")

var navi_cate_sub4_1_code = new Array ("e51cfa0e")
var navi_cate_sub4_1_menu_subject = new Array ("노인장기요양보험제도")
var navi_cate_sub4_1_link_url = new Array ("/page/sub4_1")
var navi_cate_sub4_1_link_target = new Array ("")
var navi_cate_sub4_1_bt1 = new Array ("")
var navi_cate_sub4_1_bt2 = new Array ("")


var navi_path_arr = new Array();
navi_path_arr['54f5e29b'] = '&gt;&gt;&gt;위례빌리지 소개'; 
navi_path_arr['6b068649'] = '&gt;&gt;&gt;인재상'; 
navi_path_arr['7d3616f4'] = '&gt;&gt;&gt;평창카운티<span>노인복지주택</span>'; 
navi_path_arr['7e9b13c6'] = '&gt;&gt;&gt;서비스 소개'; 
navi_path_arr['92b2bb3c'] = '&gt;&gt;&gt;시설 안내'; 
navi_path_arr['a2a15909'] = '&gt;&gt;&gt;서비스 안내'; 
navi_path_arr['b211cc3f'] = '&gt;&gt;&gt;입주 안내·접수'; 
navi_path_arr['c10f4fd5'] = '&gt;&gt;&gt;비전체계'; 
navi_path_arr['dec9c651'] = '&gt;&gt;&gt;고객의 소리'; 
navi_path_arr['e51cfa0e'] = '&gt;&gt;&gt;노인장기요양보험제도'; 
navi_path_arr['ff741636'] = '&gt;&gt;&gt;자원봉사안내'; 
navi_path_arr['pcc_even'] = '&gt;&gt;&gt;평창카운티'; 
navi_path_arr['pcc_guid'] = '&gt;&gt;&gt;평창 카운티 소개'; 
navi_path_arr['Seocho_D'] = '&gt;&gt;&gt;서초 빌리지 소개'; 
navi_path_arr['Seocho_R'] = '&gt;&gt;&gt;서초입소안내ㆍ접수'; 
navi_path_arr['Seocho_s'] = '&gt;&gt;&gt;서초서비스·시설 안내'; 
navi_path_arr['sub00_00'] = '&gt;&gt;서초 빌리지<span>요양시설</span>'; 
navi_path_arr['sub03_2'] = '&gt;&gt;&gt;강동케어센터 소개'; 
navi_path_arr['sub03_3'] = '&gt;&gt;&gt;위례케어센터 소개'; 
navi_path_arr['sub05_1'] = '&gt;&gt;&gt;프로그램/식단표'; 
navi_path_arr['sub05_3'] = '&gt;&gt;&gt;견학안내'; 
navi_path_arr['sub05_6'] = '&gt;&gt;&gt;개소 예정 사업장 안내'; 
navi_path_arr['sub1_1_1'] = '&gt;&gt;&gt;회사소개'; 
navi_path_arr['sub1_1_2'] = '&gt;&gt;&gt;CEO 인사말'; 
navi_path_arr['sub1_1_3'] = '&gt;&gt;&gt;오시는 길'; 
navi_path_arr['sub1_2_1'] = '&gt;&gt;&gt;게시판'; 
navi_path_arr['sub1_2_2'] = '&gt;&gt;&gt;활동후기'; 
navi_path_arr['sub1_2_3'] = '&gt;&gt;&gt;자원봉사 신청'; 
navi_path_arr['sub1_3_1'] = '&gt;&gt;&gt;인재채용'; 
navi_path_arr['sub1_3_2'] = '&gt;&gt;&gt;직무소개'; 
navi_path_arr['sub1_3_3'] = '&gt;&gt;&gt;채용공고'; 
navi_path_arr['sub1_4'] = '&gt;&gt;&gt;공지/공시'; 
navi_path_arr['sub2_1'] = '&gt;&gt;&gt;케어센터<span>주.야간보호센터</span>'; 
navi_path_arr['sub2_2_1'] = '&gt;&gt;&gt;시설안내'; 
navi_path_arr['sub2_3'] = '&gt;&gt;&gt;상담신청'; 
navi_path_arr['sub2_3_1'] = '&gt;&gt;&gt;상담신청'; 
navi_path_arr['sub3_1'] = '&gt;&gt;&gt;위례 빌리지<span>요양시설</span>'; 
navi_path_arr['sub3_2_1'] = '&gt;&gt;&gt;서비스·시설 안내'; 
navi_path_arr['sub3_3'] = '&gt;&gt;&gt;입소안내ㆍ접수'; 
navi_path_arr['sub4_1'] = '&gt;&gt;&gt;노인장기요양보험제도'; 
navi_path_arr['sub4_4'] = '&gt;&gt;&gt;인재풀 등록'; 
